from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie, QPixmap, QColor, QIcon
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import Qt
from classes import modal,Logica, Worker, usuario, Worker
from .CambiarContrasenia import UIContraseniaModal
from resources import *

class UICuentaModal(modal):

    def __init__(self,**kwargs):
        super(UICuentaModal,self).__init__(**kwargs)
        self.usuario = usuario()

    def setupUI(self):
        CuentaModal = self
        CuentaModal.setObjectName("CuentaModal")
        CuentaModal.setWindowModality(QtCore.Qt.WindowModal)
        CuentaModal.resize(385, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CuentaModal.sizePolicy().hasHeightForWidth())
        CuentaModal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        CuentaModal.setFont(font)
        CuentaModal.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../.designer/if_16_1751363.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CuentaModal.setWindowIcon(icon)
        CuentaModal.setStyleSheet("background-color: rgb(255, 255, 255);")
        CuentaModal.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.verticalLayout = QtWidgets.QVBoxLayout(CuentaModal)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainFrame = QtWidgets.QFrame(CuentaModal)
        self.MainFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MainFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleFrame = QtWidgets.QFrame(self.MainFrame)
        self.TitleFrame.setMaximumSize(QtCore.QSize(16777215, 116))
        self.TitleFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.TitleFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TitleFrame.setObjectName("TitleFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.TitleFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSCADA = QtWidgets.QLabel(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSCADA.sizePolicy().hasHeightForWidth())
        self.lblSCADA.setSizePolicy(sizePolicy)
        self.lblSCADA.setMinimumSize(QtCore.QSize(150, 116))
        self.lblSCADA.setMaximumSize(QtCore.QSize(16777215, 116))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.lblSCADA.setFont(font)
        self.lblSCADA.setAutoFillBackground(False)
        self.lblSCADA.setStyleSheet("color: rgb(255, 255, 0);background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblSCADA.setObjectName("lblSCADA")
        self.gridLayout.addWidget(self.lblSCADA, 0, 1, 1, 1)
        self.ExitFrame = QtWidgets.QFrame(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExitFrame.sizePolicy().hasHeightForWidth())
        self.ExitFrame.setSizePolicy(sizePolicy)
        self.ExitFrame.setMinimumSize(QtCore.QSize(0, 116))
        self.ExitFrame.setMaximumSize(QtCore.QSize(16777215, 116))
        self.ExitFrame.setStyleSheet("background-color: rgb(65, 105, 225);")
        self.ExitFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ExitFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExitFrame.setLineWidth(0)
        self.ExitFrame.setObjectName("ExitFrame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ExitFrame)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblIIE = QtWidgets.QLabel(self.ExitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblIIE.sizePolicy().hasHeightForWidth())
        self.lblIIE.setSizePolicy(sizePolicy)
        self.lblIIE.setMaximumSize(QtCore.QSize(16777215, 116))
        self.lblIIE.setStyleSheet("background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblIIE.setText("")
        self.lblIIE.setPixmap(QtGui.QPixmap(":/source/img/iiie.png"))
        self.lblIIE.setScaledContents(False)
        self.lblIIE.setAlignment(QtCore.Qt.AlignCenter)
        self.lblIIE.setObjectName("lblIIE")
        self.gridLayout_4.addWidget(self.lblIIE, 0, 0, 2, 1)
        self.btnExit = QtWidgets.QPushButton(self.ExitFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setMaximumSize(QtCore.QSize(32, 32))
        self.btnExit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.btnExit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/Cancelar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnExit.setIcon(icon1)
        self.btnExit.setIconSize(QtCore.QSize(24, 24))
        self.btnExit.setFlat(True)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout_4.addWidget(self.btnExit, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.ExitFrame, 0, 2, 1, 1)
        self.lblUDB = QtWidgets.QLabel(self.TitleFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblUDB.sizePolicy().hasHeightForWidth())
        self.lblUDB.setSizePolicy(sizePolicy)
        self.lblUDB.setMinimumSize(QtCore.QSize(0, 116))
        self.lblUDB.setMaximumSize(QtCore.QSize(16777215, 116))
        self.lblUDB.setStyleSheet("background-color: rgb(65, 105, 225);\n"
"margin:0px;")
        self.lblUDB.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblUDB.setText("")
        self.lblUDB.setPixmap(QtGui.QPixmap(":/source/img/logo.png"))
        self.lblUDB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUDB.setObjectName("lblUDB")
        self.gridLayout.addWidget(self.lblUDB, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.TitleFrame)
        self.lblTitle = QtWidgets.QLabel(self.MainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitle.sizePolicy().hasHeightForWidth())
        self.lblTitle.setSizePolicy(sizePolicy)
        self.lblTitle.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setStyleSheet("margin-top:5px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout_2.addWidget(self.lblTitle)
        self.ContentBox = QtWidgets.QGroupBox(self.MainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContentBox.sizePolicy().hasHeightForWidth())
        self.ContentBox.setSizePolicy(sizePolicy)
        self.ContentBox.setMinimumSize(QtCore.QSize(300, 0))
        self.ContentBox.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ContentBox.setFont(font)
        self.ContentBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ContentBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.ContentBox.setFlat(True)
        self.ContentBox.setObjectName("ContentBox")
        self.ContentLayout = QtWidgets.QVBoxLayout(self.ContentBox)
        self.ContentLayout.setContentsMargins(0, 0, 0, 0)
        self.ContentLayout.setSpacing(0)
        self.ContentLayout.setObjectName("ContentLayout")
        self.ContentFrame = QtWidgets.QFrame(self.ContentBox)
        self.ContentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ContentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ContentFrame.setObjectName("ContentFrame")
        self.lblNombre = QtWidgets.QLabel(self.ContentFrame)
        self.lblNombre.setGeometry(QtCore.QRect(60, 40, 75, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNombre.setObjectName("lblNombre")
        self.lblTipo = QtWidgets.QLabel(self.ContentFrame)
        self.lblTipo.setGeometry(QtCore.QRect(60, 160, 75, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipo.setFont(font)
        self.lblTipo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTipo.setObjectName("lblTipo")
        self.btnAceptar_2 = QtWidgets.QPushButton(self.ContentFrame)
        self.btnAceptar_2.setGeometry(QtCore.QRect(110, 250, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAceptar_2.setFont(font)
        self.btnAceptar_2.setStyleSheet("border:1px solid green;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/img/OK.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar_2.setIcon(icon2)
        self.btnAceptar_2.setIconSize(QtCore.QSize(24, 24))
        self.btnAceptar_2.setShortcut("")
        self.btnAceptar_2.setCheckable(False)
        self.btnAceptar_2.setFlat(True)
        self.btnAceptar_2.setObjectName("btnAceptar_2")
        self.lblEmail = QtWidgets.QLabel(self.ContentFrame)
        self.lblEmail.setGeometry(QtCore.QRect(60, 120, 75, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail.setFont(font)
        self.lblEmail.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblEmail.setObjectName("lblEmail")
        self.lblUsuario = QtWidgets.QLabel(self.ContentFrame)
        self.lblUsuario.setGeometry(QtCore.QRect(60, 80, 75, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblUsuario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblUsuario.setObjectName("lblUsuario")
        self.lblTipo_2 = QtWidgets.QLabel(self.ContentFrame)
        self.lblTipo_2.setGeometry(QtCore.QRect(54, 200, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipo_2.setFont(font)
        self.lblTipo_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTipo_2.setObjectName("lblTipo_2")
        self.label_4 = QtWidgets.QLabel(self.ContentFrame)
        self.label_4.setGeometry(QtCore.QRect(145, 160, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnAceptar_3 = QtWidgets.QPushButton(self.ContentFrame)
        self.btnAceptar_3.setGeometry(QtCore.QRect(140, 195, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnAceptar_3.setFont(font)
        self.btnAceptar_3.setStyleSheet("border:1px solid green;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/source/img/changepass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAceptar_3.setIcon(icon3)
        self.btnAceptar_3.setIconSize(QtCore.QSize(24, 24))
        self.btnAceptar_3.setShortcut("")
        self.btnAceptar_3.setCheckable(False)
        self.btnAceptar_3.setFlat(True)
        self.btnAceptar_3.setObjectName("btnAceptar_3")
        self.txtNombre = QtWidgets.QLineEdit(self.ContentFrame)
        self.txtNombre.setGeometry(QtCore.QRect(140, 40, 101, 21))
        self.txtNombre.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtNombre.setObjectName("txtNombre")
        self.txtUsuario = QtWidgets.QLineEdit(self.ContentFrame)
        self.txtUsuario.setGeometry(QtCore.QRect(140, 80, 101, 21))
        self.txtUsuario.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtUsuario.setObjectName("txtUsuario")
        self.Status = QtWidgets.QLabel(self.ContentFrame)
        self.Status.setGeometry(QtCore.QRect(120, 245, 51, 51))
        self.Status.setMaximumSize(QtCore.QSize(64, 64))
        self.Status.setText("")
        self.Status.setPixmap(QtGui.QPixmap(":/source/img/Cargando.gif"))
        self.Status.setScaledContents(True)
        self.Status.setObjectName("Status")
        self.txtEmail = QtWidgets.QLineEdit(self.ContentFrame)
        self.txtEmail.setGeometry(QtCore.QRect(140, 120, 101, 21))
        self.txtEmail.setStyleSheet("border-bottom:1px solid black;border-top:none;")
        self.txtEmail.setObjectName("txtEmail")
        self.ContentLayout.addWidget(self.ContentFrame)
        self.verticalLayout_2.addWidget(self.ContentBox, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.MainFrame)

        self.retranslateUi(CuentaModal)
        QtCore.QMetaObject.connectSlotsByName(CuentaModal)
        self.Status.hide()
        self.center()

        self.shortcut = QtWidgets.QShortcut(Qt.Key_Return,self)
        self.shortcut.activated.connect(self.validarUsuario)

        # movie
        self.movie = QMovie(":/source/img/Cargando.gif") # 80 ,200
        self.movie.setScaledSize(QtCore.QSize(48,48))
        self.Status.setMovie(self.movie)
        self.Status.hide()
        
        #listener
        self.parent.signals.resize.connect(self.center)
        self.btnExit.clicked.connect(self.exit)
        self.btnAceptar_2.clicked.connect(self.validarUsuario)
        self.btnAceptar_3.clicked.connect(self.cambiarContrasenia)

    def disconnectSignals(self):
        self.parent.signals.resize.disconnect(self.center)
        self.btnExit.clicked.disconnect(self.exit)
        self.btnAceptar_2.clicked.disconnect(self.validarUsuario)

    def cambiarContrasenia(self):
        UIPass = UIContraseniaModal(**{"Parent":self.parent})
        UIPass.show()
        
    def showEvent(self,evt):
        self.txtNombre.setText(self.session.nombres)
        self.txtEmail.setText(self.session.email)
        self.txtUsuario.setText(self.session.usuario)
        self.label_4.setText(self.session.tipo)
        self.usuario.id = self.session.id
        self.usuario.tipo = self.session.tipo
        if self.session.usuario == "administrador.scada":
           self.txtUsuario.setEnabled(False)

    def validarUsuario(self):
        try:
            self.usuario.nombres = self.txtNombre.text()
            self.usuario.usuario = self.txtUsuario.text()
            self.usuario.email = self.txtEmail.text()
        except ValueError as vError:
            QMessageBox.warning(self,"¡Error!",str(vError))
            return
        reply = self.prompt("Confirmacion","¿Son estos datos correctos?")
        if reply == QMessageBox.Yes:
            self.btnAceptar_2.hide()
            self.Status.show()
            self.movie.start()
            worker = Worker(Logica.actualizarUsuario,**{"access_token":self.session.access_token,"data":self.usuario.toJSON()})
            worker.signals.finished.connect(self.validarUsuarioAction)
            self.threadpool.start(worker)

    def validarUsuarioAction(self,response):
        self.btnAceptar_2.show()
        self.Status.hide()
        self.movie.stop()
        if isinstance(response,Exception):
            QMessageBox.warning(self,"¡Error!",str(response))
            return
        if response["Success"] == 'false':
            QMessageBox.warning(self,'¡Error!',response["Message"])
            return
        QMessageBox.information(self,"¡Aviso!","Datos actualizados")
        self.close()

    def retranslateUi(self, CuentaModal):
        _translate = QtCore.QCoreApplication.translate
        CuentaModal.setWindowTitle(_translate("CuentaModal", "Sistema SCADA"))
        self.lblSCADA.setText(_translate("CuentaModal", "SCADA"))
        self.lblTitle.setText(_translate("CuentaModal", "Cuenta"))
        self.ContentBox.setTitle(_translate("CuentaModal", "Información"))
        self.lblNombre.setText(_translate("CuentaModal", "Nombre:"))
        self.lblTipo.setText(_translate("CuentaModal", "Tipo:"))
        self.btnAceptar_2.setText(_translate("CuentaModal", "OK"))
        self.lblEmail.setText(_translate("CuentaModal", "Email:"))
        self.lblUsuario.setText(_translate("CuentaModal", "Usuario:"))
        self.lblTipo_2.setText(_translate("CuentaModal", "Contraseña:"))
        self.label_4.setText(_translate("CuentaModal", "Email"))
        self.btnAceptar_3.setText(_translate("CuentaModal", "Cambiar"))
