from .AIWidget import UIAIVariable
from .AOWidget import UIAOVariable
from .DIWidget import UIDIVariable
from .DOWidget import UIDOVariable
from .Dispositivo import UIDispositivoWidget
from .DispositivoWidget import UIDispositivoModalWidget
from .ProyectoWidget import UIWidgetP
from .VariableWidget import UIVariableWidget
from .UsuarioWidget import UIUsuarioWidget