from PyQt5 import QtCore, QtGui, QtWidgets
from classes import widget, usuario
from functools import partial
from resources import *

class UIUsuarioWidget(widget):

    def __init__(self,usr:usuario):
        super(UIUsuarioWidget,self).__init__()
        self.usuario = usr
        self.setupUi()

    def setupUi(self):
        UsuarioWidget = self
        UsuarioWidget.setObjectName("UsuarioWidget")
        UsuarioWidget.resize(617, 41)
        UsuarioWidget.setMinimumSize(QtCore.QSize(150, 41))
        UsuarioWidget.setMaximumSize(QtCore.QSize(16777215, 41))
        self.MainFrame = QtWidgets.QFrame(UsuarioWidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 621, 41))
        self.MainFrame.setMinimumSize(QtCore.QSize(621, 41))
        self.MainFrame.setMaximumSize(QtCore.QSize(621, 41))
        self.MainFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MainFrame.setLineWidth(1)
        self.MainFrame.setObjectName("MainFrame")
        self.lblNombreScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblNombreScroll.setGeometry(QtCore.QRect(1, 8, 125, 25))
        self.lblNombreScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblNombreScroll.setMaximumSize(QtCore.QSize(125, 25))
        self.lblNombreScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblNombreScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblNombreScroll.setLineWidth(0)
        self.lblNombreScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblNombreScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblNombreScroll.setWidgetResizable(True)
        self.lblNombreScroll.setObjectName("lblNombreScroll")
        self.ScrollNombreLayout = QtWidgets.QWidget()
        self.ScrollNombreLayout.setGeometry(QtCore.QRect(0, 0, 125, 25))
        self.ScrollNombreLayout.setObjectName("ScrollNombreLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.ScrollNombreLayout)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblNombre = QtWidgets.QLabel(self.ScrollNombreLayout)
        self.lblNombre.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setLineWidth(0)
        self.lblNombre.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblNombre.setWordWrap(True)
        self.lblNombre.setIndent(5)
        self.lblNombre.setObjectName("lblNombre")
        self.vboxlayout.addWidget(self.lblNombre)
        self.lblNombreScroll.setWidget(self.ScrollNombreLayout)
        self.lblTipo = QtWidgets.QLabel(self.MainFrame)
        self.lblTipo.setGeometry(QtCore.QRect(400, 8, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipo.setFont(font)
        self.lblTipo.setStyleSheet("padding-top:5px;")
        self.lblTipo.setLineWidth(0)
        self.lblTipo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTipo.setIndent(-1)
        self.lblTipo.setObjectName("lblTipo")
        #btnEditar
        self.btnEditar = QtWidgets.QPushButton(self.MainFrame)
        self.btnEditar.setGeometry(QtCore.QRect(545, 5, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditar.sizePolicy().hasHeightForWidth())
        self.btnEditar.setSizePolicy(sizePolicy)
        self.btnEditar.setMinimumSize(QtCore.QSize(32, 32))
        self.btnEditar.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEditar.setFont(font)
        self.btnEditar.setStyleSheet("")
        self.btnEditar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/edituser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon)
        self.btnEditar.setIconSize(QtCore.QSize(24, 24))
        self.btnEditar.setShortcut("")
        self.btnEditar.setCheckable(False)
        self.btnEditar.setFlat(True)
        self.btnEditar.setObjectName("btnEditar")
        #btnEliminar
        self.btnEliminar = QtWidgets.QPushButton(self.MainFrame)
        self.btnEliminar.setGeometry(QtCore.QRect(580, 5, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEliminar.sizePolicy().hasHeightForWidth())
        self.btnEliminar.setSizePolicy(sizePolicy)
        self.btnEliminar.setMinimumSize(QtCore.QSize(32, 32))
        self.btnEliminar.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setStyleSheet("")
        self.btnEliminar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/deluser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon1)
        self.btnEliminar.setIconSize(QtCore.QSize(24, 24))
        self.btnEliminar.setShortcut("")
        self.btnEliminar.setCheckable(False)
        self.btnEliminar.setFlat(True)
        self.btnEliminar.setObjectName("btnEliminar")
        #btnHabilitar
        self.btnHabilitar = QtWidgets.QPushButton(self.MainFrame)
        self.btnHabilitar.setGeometry(QtCore.QRect(510, 5, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHabilitar.sizePolicy().hasHeightForWidth())
        self.btnHabilitar.setSizePolicy(sizePolicy)
        self.btnHabilitar.setMinimumSize(QtCore.QSize(32, 32))
        self.btnHabilitar.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnHabilitar.setFont(font)
        self.btnHabilitar.setStyleSheet("")
        self.btnHabilitar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/source/img/allow.png" if not self.usuario.enabled else ":/source/img/denied.png" ), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHabilitar.setIcon(icon2)
        self.btnHabilitar.setIconSize(QtCore.QSize(24, 24))
        self.btnHabilitar.setShortcut("")
        self.btnHabilitar.setCheckable(False)
        self.btnHabilitar.setFlat(True)
        self.btnHabilitar.setObjectName("btnHabilitar")
        self.lblEmailScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblEmailScroll.setGeometry(QtCore.QRect(270, 5, 125, 35))
        self.lblEmailScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblEmailScroll.setMaximumSize(QtCore.QSize(125, 50))
        self.lblEmailScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblEmailScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblEmailScroll.setLineWidth(0)
        self.lblEmailScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblEmailScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblEmailScroll.setWidgetResizable(True)
        self.lblEmailScroll.setObjectName("lblEmailScroll")
        self.ScrollEmailLayout = QtWidgets.QWidget()
        self.ScrollEmailLayout.setGeometry(QtCore.QRect(0, 0, 193, 22))
        self.ScrollEmailLayout.setObjectName("ScrollEmailLayout")
        self._3 = QtWidgets.QVBoxLayout(self.ScrollEmailLayout)
        self._3.setContentsMargins(0, 0, 0, 0)
        self._3.setSpacing(0)
        self._3.setObjectName("_3")
        self.lblEmail = QtWidgets.QLabel(self.ScrollEmailLayout)
        self.lblEmail.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblEmail.setFont(font)
        self.lblEmail.setLineWidth(0)
        self.lblEmail.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblEmail.setWordWrap(True)
        self.lblEmail.setIndent(5)
        self.lblEmail.setObjectName("lblEmail")
        self._3.addWidget(self.lblEmail)
        self.lblEmailScroll.setWidget(self.ScrollEmailLayout)
        self.lblUsuarioScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblUsuarioScroll.setGeometry(QtCore.QRect(115, 8, 150, 25))
        self.lblUsuarioScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblUsuarioScroll.setMaximumSize(QtCore.QSize(150, 25))
        self.lblUsuarioScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblUsuarioScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblUsuarioScroll.setLineWidth(0)
        self.lblUsuarioScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblUsuarioScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblUsuarioScroll.setWidgetResizable(True)
        self.lblUsuarioScroll.setObjectName("lblUsuarioScroll")
        self.ScrollUsuarioLayout = QtWidgets.QWidget()
        self.ScrollUsuarioLayout.setGeometry(QtCore.QRect(0, 0, 150, 25))
        self.ScrollUsuarioLayout.setObjectName("ScrollUsuarioLayout")
        self._4 = QtWidgets.QVBoxLayout(self.ScrollUsuarioLayout)
        self._4.setContentsMargins(0, 0, 0, 0)
        self._4.setSpacing(0)
        self._4.setObjectName("_4")
        self.lblUsuario = QtWidgets.QLabel(self.ScrollUsuarioLayout)
        self.lblUsuario.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setLineWidth(0)
        self.lblUsuario.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblUsuario.setWordWrap(True)
        self.lblUsuario.setIndent(5)
        self.lblUsuario.setObjectName("lblUsuario")
        self._4.addWidget(self.lblUsuario)
        self.lblUsuarioScroll.setWidget(self.ScrollUsuarioLayout)

        self.btnHabilitar.hide()
        self.btnEditar.hide()
        self.btnEliminar.hide()

        self.retranslateUi(UsuarioWidget)
        QtCore.QMetaObject.connectSlotsByName(UsuarioWidget)

        #listener

        self.btnHabilitar.clicked.connect(self.actualizarEstadoUsuario)
        self.btnEditar.clicked.connect(self.editarUsuario)
        self.btnEliminar.clicked.connect(self.eliminarUsuario)

    def actualizarEstadoUsuario(self):
        reply = self.prompt("Confirmacion","¿Habilitar este usuario?" if not self.usuario.enabled else "¿Deshabilitar este usuario?")
        if not reply == QtWidgets.QMessageBox.Yes:
            return
        if not self.usuario.enabled:
            self.signals.enable.emit(self.usuario)
        else:
            self.signals.disable.emit(self.usuario)

    def editarUsuario(self):
        reply = self.prompt("Confirmacion","¿Editar este usuario?")
        if  reply == QtWidgets.QMessageBox.Yes:
            self.signals.edit.emit(self.usuario)
    
    def eliminarUsuario(self):
        reply = self.prompt("Confirmacion","¿Editar este usuario?")
        if  reply == QtWidgets.QMessageBox.Yes:
            self.signals.delete.emit(self.usuario)
    
    def updateUI(self,usr:usuario):
        self.usuario = usr     
        _translate = QtCore.QCoreApplication.translate  
        self.lblNombre.setText(_translate("UsuarioWidget", self.usuario.nombres))
        self.lblTipo.setText(_translate("UsuarioWidget", self.usuario.tipo))
        self.lblEmail.setText(_translate("UsuarioWidget", "-" if self.usuario.email == "" else self.usuario.email))
        self.lblUsuario.setText(_translate("UsuarioWidget", self.usuario.usuario)) 
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/allow.png" if not self.usuario.enabled else ":/source/img/denied.png" ), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnHabilitar.setIcon(icon)

    def showEvent(self,evt):
        
        currentUser = self.session.usuario
        currentType = self.session.tipo
        showUser = self.usuario.usuario
        showType = self.usuario.tipo

        if (currentUser == "administrador.scada" and not showUser == "administrador.scada") or (currentType == "Administrador" and not showType == "Administrador" ):
            self.btnHabilitar.show()
            self.btnEditar.show()
            self.btnEliminar.show()
        if (currentUser == showUser):
            self.btnEditar.show()
            #self.btnHabilitar.clicked.disconnect(self.actualizarEstadoUsuario)
            #self.btnHabilitar.deleteLater()
            #self.btnEliminar.deleteLater()

    def disconnectSignals(self):
        self.btnHabilitar.clicked.disconnect(self.actualizarEstadoUsuario)
        self.btnEditar.clicked.disconnect(self.editarUsuario)
    
    def sizeHint(self):
        return QtCore.QSize(621,41)

    def retranslateUi(self, UsuarioWidget):
        _translate = QtCore.QCoreApplication.translate
        UsuarioWidget.setWindowTitle(_translate("UsuarioWidget", "Form"))
        self.lblNombre.setText(_translate("UsuarioWidget", self.usuario.nombres))
        self.lblTipo.setText(_translate("UsuarioWidget", self.usuario.tipo))
        self.lblEmail.setText(_translate("UsuarioWidget", "-" if self.usuario.email == "" else self.usuario.email))
        self.lblUsuario.setText(_translate("UsuarioWidget", self.usuario.usuario))
