from PyQt5 import QtCore, QtGui, QtWidgets
from classes import widget, variable
from functools import partial
from resources import *

class UIVariableWidget(widget):

    def __init__(self,var:variable):
        super(UIVariableWidget,self).__init__()
        self.variable = var
        self.setupUi()

    def setupUi(self):
        VariableWidget = self
        VariableWidget.setObjectName("VariableWidget")
        VariableWidget.resize(455, 41)
        VariableWidget.setMinimumSize(QtCore.QSize(150, 41))
        VariableWidget.setMaximumSize(QtCore.QSize(16777215, 41))
        self.MainFrame = QtWidgets.QFrame(VariableWidget)
        self.MainFrame.setGeometry(QtCore.QRect(0, 0, 455, 41))
        self.MainFrame.setMinimumSize(QtCore.QSize(450, 41))
        self.MainFrame.setMaximumSize(QtCore.QSize(16666, 41))
        self.MainFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.MainFrame.setLineWidth(1)
        self.MainFrame.setObjectName("MainFrame")
        self.lblNombreScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblNombreScroll.setGeometry(QtCore.QRect(1, 5, 75, 25))
        self.lblNombreScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblNombreScroll.setMaximumSize(QtCore.QSize(100, 25))
        self.lblNombreScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblNombreScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblNombreScroll.setLineWidth(0)
        self.lblNombreScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblNombreScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblNombreScroll.setWidgetResizable(True)
        self.lblNombreScroll.setObjectName("lblNombreScroll")
        self.ScrollNombreLayout = QtWidgets.QWidget()
        self.ScrollNombreLayout.setGeometry(QtCore.QRect(0, 0, 75, 25))
        self.ScrollNombreLayout.setObjectName("ScrollNombreLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.ScrollNombreLayout)
        self.vboxlayout.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lblNombre = QtWidgets.QLabel(self.ScrollNombreLayout)
        self.lblNombre.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblNombre.setFont(font)
        self.lblNombre.setLineWidth(0)
        self.lblNombre.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblNombre.setWordWrap(True)
        self.lblNombre.setIndent(5)
        self.lblNombre.setObjectName("lblNombre")
        self.vboxlayout.addWidget(self.lblNombre)
        self.lblNombreScroll.setWidget(self.ScrollNombreLayout)
        self.lblTipo = QtWidgets.QLabel(self.MainFrame)
        self.lblTipo.setGeometry(QtCore.QRect(160, 5, 60, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblTipo.setFont(font)
        self.lblTipo.setStyleSheet("padding-top:5px;")
        self.lblTipo.setLineWidth(0)
        self.lblTipo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTipo.setIndent(-1)
        self.lblTipo.setObjectName("lblTipo")
        self.lblColor = QtWidgets.QLabel(self.MainFrame)
        self.lblColor.setGeometry(QtCore.QRect(230, 5, 75, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblColor.setFont(font)
        self.lblColor.setStyleSheet("padding-top:5px;")
        self.lblColor.setLineWidth(0)
        self.lblColor.setAlignment(QtCore.Qt.AlignCenter)
        self.lblColor.setIndent(-1)
        self.lblColor.setObjectName("lblColor")
        self.lblSel = QtWidgets.QLabel(self.MainFrame)
        self.lblSel.setGeometry(QtCore.QRect(310, 5, 70, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblSel.setFont(font)
        self.lblSel.setStyleSheet("padding-top:5px;")
        self.lblSel.setLineWidth(0)
        self.lblSel.setAlignment(QtCore.Qt.AlignCenter)
        self.lblSel.setIndent(-1)
        self.lblSel.setObjectName("lblSel")
        self.btnEditar = QtWidgets.QPushButton(self.MainFrame)
        self.btnEditar.setGeometry(QtCore.QRect(390, 5, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEditar.sizePolicy().hasHeightForWidth())
        self.btnEditar.setSizePolicy(sizePolicy)
        self.btnEditar.setMinimumSize(QtCore.QSize(32, 32))
        self.btnEditar.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEditar.setFont(font)
        self.btnEditar.setStyleSheet("")
        self.btnEditar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/source/img/Editar-SM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditar.setIcon(icon)
        self.btnEditar.setIconSize(QtCore.QSize(24, 24))
        self.btnEditar.setShortcut("")
        self.btnEditar.setCheckable(False)
        self.btnEditar.setFlat(True)
        self.btnEditar.setObjectName("btnEditar")
        self.btnEliminar = QtWidgets.QPushButton(self.MainFrame)
        self.btnEliminar.setGeometry(QtCore.QRect(420, 5, 32, 32))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnEliminar.sizePolicy().hasHeightForWidth())
        self.btnEliminar.setSizePolicy(sizePolicy)
        self.btnEliminar.setMinimumSize(QtCore.QSize(32, 32))
        self.btnEliminar.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setStyleSheet("")
        self.btnEliminar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/source/img/Eliminar-SM.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEliminar.setIcon(icon1)
        self.btnEliminar.setIconSize(QtCore.QSize(24, 24))
        self.btnEliminar.setShortcut("")
        self.btnEliminar.setCheckable(False)
        self.btnEliminar.setFlat(True)
        self.btnEliminar.setObjectName("btnEliminar")
        self.lblVariableScroll = QtWidgets.QScrollArea(self.MainFrame)
        self.lblVariableScroll.setGeometry(QtCore.QRect(75, 5, 75, 25))
        self.lblVariableScroll.setMinimumSize(QtCore.QSize(65, 20))
        self.lblVariableScroll.setMaximumSize(QtCore.QSize(100, 25))
        self.lblVariableScroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblVariableScroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblVariableScroll.setLineWidth(0)
        self.lblVariableScroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lblVariableScroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.lblVariableScroll.setWidgetResizable(True)
        self.lblVariableScroll.setObjectName("lblVariableScroll")
        self.ScrollVariableLayout = QtWidgets.QWidget()
        self.ScrollVariableLayout.setGeometry(QtCore.QRect(0, 0, 75, 25))
        self.ScrollVariableLayout.setObjectName("ScrollVariableLayout")
        self._2 = QtWidgets.QVBoxLayout(self.ScrollVariableLayout)
        self._2.setContentsMargins(0, 0, 0, 0)
        self._2.setSpacing(0)
        self._2.setObjectName("_2")
        self.lblVariable = QtWidgets.QLabel(self.ScrollVariableLayout)
        self.lblVariable.setMaximumSize(QtCore.QSize(16666672, 16666672))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblVariable.setFont(font)
        self.lblVariable.setLineWidth(0)
        self.lblVariable.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblVariable.setWordWrap(True)
        self.lblVariable.setIndent(5)
        self.lblVariable.setObjectName("lblVariable")
        self._2.addWidget(self.lblVariable)
        self.lblVariableScroll.setWidget(self.ScrollVariableLayout)

        self.retranslateUi(VariableWidget)
        QtCore.QMetaObject.connectSlotsByName(VariableWidget)
        self.btnEditar.clicked.connect(partial(self.edit,"Confirmacion","¿Editar esta variable?"))
        self.btnEliminar.clicked.connect(partial(self.delete,"Confirmacion","¿Eliminar esta variable?"))

    def disconnectSignals(self):
        self.btnEditar.clicked.disconnect()
        self.btnEliminar.clicked.disconnect()
        del self.variable

    def updateUI(self,var:variable):
        _translate = QtCore.QCoreApplication.translate
        self.variable = var
        self.lblNombre.setText(_translate("VariableWidget", self.variable.nombre))
        self.lblTipo.setText(_translate("VariableWidget","Lectura" if not self.variable.output else "Escritura"))
        self.lblColor.setText(_translate("VariableWidget", "-" if self.variable.displayColor == None else self.variable.displayColor))
        self.lblSel.setText(_translate("VariableWidget", "Analogica" if self.variable.analogic else "Digital"))
        self.lblVariable.setText(_translate("VariableWidget", self.variable.pin))

    def retranslateUi(self, VariableWidget):
        _translate = QtCore.QCoreApplication.translate
        VariableWidget.setWindowTitle(_translate("VariableWidget", "Form"))
        self.lblNombre.setText(_translate("VariableWidget", self.variable.nombre))
        self.lblTipo.setText(_translate("VariableWidget","Lectura" if not self.variable.output else "Escritura"))
        self.lblColor.setText(_translate("VariableWidget", "-" if self.variable.displayColor == None else self.variable.displayColor))
        self.lblSel.setText(_translate("VariableWidget", "Analogica" if self.variable.analogic else "Digital"))
        self.lblVariable.setText(_translate("VariableWidget", self.variable.pin))
